kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: >-
      https://github.com/VictorFernandezArias/gitops-test-amq.git
    openshift.io/generated-by: OpenShiftWebConsole
  name: activar-personas
  labels:
    app: activar-personas
    app.kubernetes.io/component: activar-personas
    app.kubernetes.io/instance: activar-personas
    app.kubernetes.io/name: activar-personas
    app.kubernetes.io/part-of: activar-personas
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-11-el7
spec:
  lookupPolicy:
    local: false
status: {}
