kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: >-
      https://gitlab.consulting.redhat.com/sclmw-proyectos/min-publico-rgp/mp-spring-amq-poc.git
    openshift.io/generated-by: OpenShiftWebConsole
  name: crear-personas
  labels:
    app: crear-personas
    app.kubernetes.io/component: crear-personas
    app.kubernetes.io/instance: crear-personas
    app.kubernetes.io/name: crear-personas
    app.kubernetes.io/part-of: crear-personas
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-11-el7
spec:
  lookupPolicy:
    local: false
status: {}
