kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: >-
      https://github.com/VictorFernandezArias/gitops-test-amq.git
    openshift.io/generated-by: OpenShiftWebConsole
  name: enviar-email-notificacion
  labels:
    app: enviar-email-notificacion
    app.kubernetes.io/component: enviar-email-notificacion
    app.kubernetes.io/instance: enviar-email-notificacion
    app.kubernetes.io/name: enviar-email-notificacion
    app.kubernetes.io/part-of: enviar-email-notificacion
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-11-el7
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'enviar-email-notificacion:latest'
  resources: {}
  successfulBuildsHistoryLimit: 1
  failedBuildsHistoryLimit: 1
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'java:openjdk-11-el7'
  postCommit: {}
  source:
    type: Git
    git:
      uri: >-
        https://github.com/VictorFernandezArias/gitops-test-amq.git
    contextDir: /enviar-email-notificacion
  runPolicy: Serial
status: {}
